# Generated by Django 4.1 on 2022-10-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_our_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experties',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='our_products',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='our_products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
